
---
- name: install and start LAMP
  hosts: LAMP
  become: yes
  vars_files:
   - vars/default.yaml

  tasks:
   - name: install prerequisites
     apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

   - name: install Apache
     apt: name=apache2 update_cache=yes state=lates

   - name: install MySql
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'mysql-server', 'python3-pymysql' ]
   
   - name: install php
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'php', 'php-mysql', 'libapache2-mod-php' ]

   - name: install php extensions
     apt: name={{ item }} update_cache=yes state=latest
     loop: "{{ php_modules }}"
   

   # need fix
   - name: create wordpress folder
     become: yes
     file:
       path: "/var/www/{{ http_host }}"
       state: directory
       owner: "www-date"
       group: "www-date"
       mode: '0755'

   - name: set up virtualhost
     template:
       src: "files/apache.conf"
       dest: "/etc/apache2/sites-avaiable/{{ http_conf }}"
     tegs: [ test ]

   - name: enable new site and disable default
     shell: /usr/sbin/a2enmod rewrite
     shell: /usr/sbin/a2ensite {{ http_conf }}
     shell: /usr/sbin/a2dissite 000-default.conf
     tegs: [ test ]




  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
 
