
---
- name: install and start LAMP
  hosts: LAMP
  become: yes
  vars_files:
   - vars/default.yaml

  tasks:
   - name: install Apache
     apt: name=apache2 update_cache=yes state=latest

   - name: enabled mod_rewrite
     apache2_module: name=rewrite state=present
     notify:
        - restart apache2

   - name: install MySql
     apt:
       name:
         - mysql
         - mysql-server
         - python3-pymysql
       state: latest

  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
 
