
---
- name: install and start LAMP
  hosts: LAMP
  become: yes
  vars_files:
   - vars/default.yaml

  tasks:
   - name: install prerequisites
     apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

   - name: install Apache
     apt: name=apache2 update_cache=yes state=latest

   - name: enabled mod_rewrite
     apache2_module: name=rewrite state=present
     notify:
        - restart apache2

   - name: install MySql
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'mysql-server', 'python3-pymysql' ]
   
   - name: install php
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'php', 'php-mysql', 'libapache2-mod-php' ]

   - name: install php extensions
     apt: name={{ item }} update_cache=yes state=latest
     loop: "{{ php_modules }}"
     tags: [ test ]
   
  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
 
