
---
- name: install and start LAMP
  hosts: LAMP
  become: yes
  vars_files:
   - vars/default.yaml

  tasks:
   - name: install prerequisites
     apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

   - name: install Apache
     apt: name=apache2 update_cache=yes state=lates

   - name: install MySql
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'mysql-server', 'python3-pymysql' ]
   
   - name: install php
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'php', 'php-mysql', 'libapache2-mod-php' ]

   - name: install php extensions
     apt: name={{ item }} update_cache=yes state=latest
     loop: "{{ php_modules }}"
   

   # need fix
   - name: create wordpress folder
     file:
       path: /var/www/{{ http_host }}
       state: directory
     # don't work
       owner: www-date
       group: www-date
       mode: '0755'
     #

   - name: set up virtualhost
     template:
       src: "files/apache.conf"
       dest: "/etc/apache2/sites-available/{{ http_conf }}"

   - name: enable new site and disable default
     shell: /usr/sbin/a2enmod rewrite
     shell: /usr/sbin/a2ensite {{ http_conf }}
     shell: /usr/sbin/a2dissite 000-default.conf

   - name: Download and unpack WordPress
     unarchive:
       src: https://wordpress.org/latest.tar.gz
       dest: "/var/www/{{ http_host }}"
       remote_src: yes
       creates: "/var/www/{{ http_host }}/wordpress"

   - name: Set up wp-config
     template:
       src: "files/wp-config.php"
       dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
     tags: [ wordpress ]


  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
 
